### ISSUE TITLE
Kenya subdivisions out of date

### ISSUE THREAD

**Issue by jiggak** [esosedi/3166#1]
As of 2014 Kenya has 47 counties instead of 8 provinces.
https://www.iso.org/obp/ui#iso:code:3166:KE

**Comment by theKashey** [comment]
Thanks. I will update regional database - https://github.com/esosedi/3166/pull/2.
It is not ready yet, I have to update rest of sources.

**Comment by theKashey** [comment]
@jiggak - just merged PR and published update. 
Kenia is up to date not. But new countries are still facing some 3166-2 certification issues - regions can be listed, but with no ISO codes.
Have a nice day.
