### ISSUE TITLE
Wrong subdivision codes in Albania

### ISSUE THREAD

**Issue by soulmerge** [esosedi/3166#10]
The iso-3166-2 subdivision codes for Albania are wrong: They should be zero-padded numeric values between 01 and 12, as specified by the standard (https://www.iso.org/obp/ui/#iso:code:3166:AL). Instead, they are given as 2-character strings like "EL" and "VL".

It looks like the error was adopted during the import from geolocated.org, which seems to use these non-ISO subdivision codes: http://geolocated.org/AL/EL/

**Comment by soulmerge** [comment]
Might I further add, that the [CLDR](http://cldr.unicode.org/) project is a much more reliable source for ISO-3166-2 codes? It uses a non-standard format ("al01" instead of "AL-01"), but tracks subdivision names (in multiple languages) and ISO codes quite accurately.

This is the file containing english subdivision names, for example: https://unicode.org/cldr/trac/browser/tags/latest/common/subdivisions/en.xml

**Comment by theKashey** [comment]
Ie does contain both numeric and non-numeric codes. Literally OpenStreetMap regions 4 and 6.
https://en.wikipedia.org/wiki/ISO_3166-2:AL

**Comment by theKashey** [comment]
Ok, it was "Before 27 November 2015". Wikipedia crawler is not reading texts, just following links with some naming format.

**Comment by soulmerge** [comment]
I don't think it is a good idea to use wikipedia as a data source in this case. The wikipedia project has no incentive to always keep up-to-date. The [CLDR](http://cldr.unicode.org/) data provided by the unicode consortium, on the other hand, is used by many, many organizations throughout the world on a daily basis.

I ran an analysis on 'i18n/dispute/UN/en.json' and found [245 invalid iso-3166-2 codes](https://pastebin.com/Xqipb8eJ) in [58 countries](https://pastebin.com/J4XtvnBs).

**Comment by theKashey** [comment]
Oh. I'll add CLDR to the sources then, but it will take a while.
