### ISSUE TITLE
How to contribute? I found some incorrect/outdated ISO_3166-2 code for Vietnam regions

### ISSUE THREAD

**Issue by bahung1221** [esosedi/3166#31]
Hi,

I just found some incorrect/outdated ISO_3166-2 code for Vietnam regions, I also checked it with OSM Overpass API and I can confirm some regions code is incorrect/outdated (Just some regions, not all Vietnam regions). 
Data reference from https://en.wikipedia.org/wiki/ISO_3166-2:VN. 
For example, on Wikipedia and OSM Overpass, `Can Tho` ISO_3166-2 code is `CT`, but on [esosedi/3166](https://raw.githubusercontent.com/esosedi/3166/master/regions/VN/en.json) it code is `48`.

You can check this code through below Overpass queries:
- Incorrent, `VN-48`: https://overpass-turbo.eu/s/11zF
- Correct, `VN-CT`:  https://overpass-turbo.eu/s/11zG

I can help to correct it, but It seems the repository has a lot of duplicates `json` data, so do I need to update all of them or do I only need to update the `data/iso3166-2.json` file?

Thank you so much!

**Comment by theKashey** [comment]
Correct - only `data/iso3166-2.json` has to be updated, the rest will be autogenerated from the given sources.

While names/translations can be automatically downloaded (`/bin/download`) the main database, the actual iso-codes, is mostly manual, as there are too many mistakes in different sources.

If wikipedia, OSM and you reckon the code should be different - feel free to change the corresponding record.
Look like only iso code has to be fixed - osmId is correct as well as geonames.
Please also consider adding wikipedia link (in OSM notation - "en:Cần_Thơ")

**Comment by bahung1221** [comment]
Thanks 🎉
