### ISSUE TITLE
Ukrainian Oblast Dnipropetrovsk encoding issue in russian language

### ISSUE THREAD

**Issue by dsimon-onventis** [esosedi/3166#36]
The Ukrainian Oblast Donetsk has the name "Днепропетров��кая область" in the Russian language, which looks to me like an encoding issue.

See: https://github.com/esosedi/3166/blob/master/regions/UA/ru.json

**Comment by theKashey** [comment]
And is the name itself correct? Донецк and Днепропертворск sounds a little differently.

**Comment by dsimon-onventis** [comment]
Thanks for the quick reply. Sorry, I have made a mistake, the english name for UA-12 is "Dnipropetrovsk" and not "Donetsk". 

I'm not a native Russian or Ukrainian, but according to [Wikipedia](https://en.wikipedia.org/wiki/Dnipropetrovsk_Oblast), the correct Ukranian name is: Дніпропетро́вська о́бласть, which is Днепропетровская область in Russian.

**Comment by theKashey** [comment]
Released in v2.3.8
