### ISSUE TITLE
Mexico City ISO 3166-2

### ISSUE THREAD

**Issue by spiderbites** [esosedi/3166#9]
Hello, thanks very much for this excellent resource.

I believe the iso for Mexico City / Ciudad de Mexico is out of date.

It is [currently listed](https://github.com/esosedi/3166/blob/master/regions/MX/en.json) as "DIF" (Distrito Federal), but I believe it should be "CMX".

Reference: https://en.wikipedia.org/wiki/ISO_3166-2:MX

**Comment by theKashey** [comment]
Thanks for heads up, I'll update it shortly.
